name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Push the frontend image on the docker registry
        uses: Ferlab-Ste-Justine/action-push-image@master
        with:
          username: chusj
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          image: chusj/cqdg-portal-ui
          tag_source: sha
          location: .
          dockerfile: Dockerfile